{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Utsav\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-31-321abfb6a98e>\", line 23, in eventFunction\n",
      "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
      "NameError: name 'imgDraw' is not defined\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from PIL import ImageTk,Image,ImageDraw\n",
    "import numpy as np\n",
    "import cv2\n",
    "\n",
    "win=tk.Tk()\n",
    "#main window\n",
    "\n",
    "w,h=500,500\n",
    "fontButton='Helvetica 20 bold'\n",
    "fontLabel='helvetica 24 bold'\n",
    "\n",
    "def eventFunction(event):\n",
    "    x=event.x\n",
    "    y=event.y\n",
    "    \n",
    "    x1=x-30\n",
    "    y1=y-30\n",
    "    x2=x+30\n",
    "    y2=y+30\n",
    "    \n",
    "    canvas.create_oval((x1,y1,x2,y2),fill='black')\n",
    "    imgDraw.ellipse((x1,y1,x2,y2),fill='white')\n",
    "\n",
    "def save():\n",
    "    imgArray=np.array(img)\n",
    "    imgArrat=cv2.resize(imgarray,(8,8))\n",
    "    \n",
    "    cv2.imwrite('data/'+str(count)+'.jpg',imgArray)\n",
    "    #file name='data/0.jpg'\n",
    "    count=count+1\n",
    "def clear():\n",
    "    canvas.delete('all')\n",
    "    img=Image.new('RGB',(w,h),(0,0,0))\n",
    "    imgDraw=ImageDraw.Draw(img)\n",
    "\n",
    "def predict()\n",
    "    \n",
    "\n",
    "canvas=tk.Canvas(win,width=w,height=h,bg='white')\n",
    "canvas.grid(row=0,column=0,columnspan=4)\n",
    "\n",
    "buttonSave=tk.Button(win,text='SAVE',bg='light sea green',fg='white',font=fontButton,command=save)\n",
    "buttonSave.grid(row=1,column=0)\n",
    "\n",
    "buttonPred=tk.Button(win,text='PREDICT',bg='blue',fg='white',font=fontButtoncommand=predict)\n",
    "buttonPred.grid(row=1,column=1)\n",
    "\n",
    "buttonClear=tk.Button(win,text='CLEAR',bg='gold',fg='white',font=fontButton,command=clear)\n",
    "buttonClear.grid(row=1,column=2)\n",
    "\n",
    "buttonExit=tk.Button(win,text='EXIT',bg='red',fg='white',font=fontButton,command=win.destroy)\n",
    "buttonExit.grid(row=1,column=3)\n",
    "\n",
    "labelStatus=tk.Label(win,text='PREDICTED DIGIT: NONE',bg='white',fg='black',font=fontLabel)\n",
    "labelStatus.grid(row=2,column=0,columnspan=4)\n",
    "\n",
    "canvas.bind('<B1-Motion>',eventFunction)\n",
    "img=Image.new('RGB',(w,h),(255,255,255))\n",
    "ImgDraw=ImageDraw.Draw(img)\n",
    "win.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
